# --------------------------------------------------------------
# INTERNATIONAL-STANDARD WEBSITE AUDIT REPORT PDF GENERATOR
# --------------------------------------------------------------
# Includes:
# - Executive Summary
# - Technical Performance Audit
# - SEO Audit
# - Security Audit
# - Accessibility Audit
# - UX & Best Practices
# - Competitor Benchmarking
# - Analytics & Tracking
# - AI Insights
# - Prioritized Action Plan
# - Compliance References
# - Audit Metadata
# --------------------------------------------------------------

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Flowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from uuid import uuid4
from datetime import datetime

# --------------------------------------------
# Font Registration
# --------------------------------------------
try:
    pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
    base_font = 'DejaVuSans'
except:
    base_font = 'Helvetica'

# --------------------------------------------
# Metadata
# --------------------------------------------
report_id = str(uuid4()).split('-')[0].upper()
now_str = datetime.now().strftime('%Y-%m-%d %H:%M')
website_url = 'TBD — Provide URL'

# --------------------------------------------
# Document Setup
# --------------------------------------------
file_name = f"Website-Audit-{report_id}.pdf"

doc = SimpleDocTemplate(
    file_name,
    pagesize=A4,
    rightMargin=16*mm,
    leftMargin=16*mm,
    topMargin=18*mm,
    bottomMargin=18*mm
)

# --------------------------------------------
# Styles
# --------------------------------------------
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleBig', fontName=base_font, fontSize=22, leading=26, alignment=TA_LEFT, spaceAfter=10))
styles.add(ParagraphStyle(name='H1', fontName=base_font, fontSize=16, leading=20, spaceAfter=6))
styles.add(ParagraphStyle(name='Body', fontName=base_font, fontSize=10.5, leading=14))
styles.add(ParagraphStyle(name='Small', fontName=base_font, fontSize=9, leading=12))

# --------------------------------------------
# Score Bar Class (Custom Flowable)
# --------------------------------------------
class ScoreBar(Flowable):
    def __init__(self, score, width=150, height=10, label=''):
        Flowable.__init__(self)
        self.score = max(0, min(100, score))
        self.width = width
        self.height = height
        self.label = label

    def draw(self):
        c = self.canv
        c.setStrokeColor(colors.grey)
        c.rect(0, 0, self.width, self.height)

        if self.score >= 85:
            fill = colors.green
        elif self.score >= 60:
            fill = colors.orange
        else:
            fill = colors.red

        c.setFillColor(fill)
        c.rect(0, 0, self.width * (self.score / 100), self.height, fill=True, stroke=False)

        c.setFillColor(colors.black)
        c.setFont(base_font, 8)
        c.drawString(self.width + 6, 1, f"{self.label}: {self.score}")

# --------------------------------------------
# Start Building the Report
# --------------------------------------------
story = []

# Title
story.append(Paragraph("🌍 International-Standard Website Audit Report", styles['TitleBig']))

# Metadata Table
meta_table = Table([
    ['Website URL', website_url],
    ['Audit Date & Time', now_str],
    ['Report ID', report_id],
    ['Generated By', 'Your SaaS Brand']
], colWidths=[45*mm, 120*mm])

meta_table.setStyle(TableStyle([
    ('FONT', (0,0), (-1,-1), base_font, 10.5),
    ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
    ('GRID', (0,0), (-1,-1), 0.3, colors.lightgrey),
]))

story.append(meta_table)
story.append(Spacer(1, 10))

# --------------------------------------------------
# 1️⃣ Executive Summary
# --------------------------------------------------
story.append(Paragraph("1️⃣ Executive Summary", styles['H1']))

scores = {
    'Overall Health Score': 0,
    'Performance': 0,
    'SEO': 0,
    'Security': 0,
    'Accessibility': 0,
    'Best Practices': 0,
    'Professional Touch': 0,
}

score_rows = []
for label, value in scores.items():
    score_rows.append([label, ScoreBar(value, width=80, height=8, label=str(value))])

score_table = Table(score_rows, colWidths=[60*mm, 100*mm])
score_table.setStyle(TableStyle([
    ('FONT', (0,0), (0,-1), base_font, 10.5),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE')
]))

story.append(score_table)
story.append(Spacer(1, 6))

summary_tbl = Table([
    ['Traffic Impact Summary', 'High impact issues (placeholder)'],
    ['Risk Level', '🟢 Low | 🟡 Medium | 🔴 High']
], colWidths=[60*mm, 100*mm])

summary_tbl.setStyle(TableStyle([
    ('FONT', (0,0), (-1,-1), base_font, 10.5),
    ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
    ('GRID', (0,0), (-1,-1), 0.3, colors.lightgrey),
]))

story.append(summary_tbl)

priority_actions = Table([
    ['Priority Actions (3–5)', '1) TBD  2) TBD  3) TBD  4) (opt)  5) (opt)']
], colWidths=[60*mm, 100*mm])

priority_actions.setStyle(TableStyle([
    ('FONT', (0,0), (-1,-1), base_font, 10.5),
    ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
    ('GRID', (0,0), (-1,-1), 0.3, colors.lightgrey),
]))

story.append(priority_actions)
story.append(PageBreak())

# --------------------------------------------------
# SECTION TEMPLATES (Performance, SEO, Security, etc.)
# --------------------------------------------------

def add_section(title, rows):
    story.append(Paragraph(title, styles["H1"]))
    tbl = Table(rows, colWidths=[60*mm, 100*mm])
    tbl.setStyle(TableStyle([
        ('FONT', (0,0), (-1,-1), base_font, 10),
        ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.25, colors.lightgrey),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F7F7F7')])
    ]))
    story.append(tbl)
    story.append(PageBreak())

#---------------------------------------------------
# 2️⃣ Performance
#---------------------------------------------------
add_section(
    "2️⃣ Technical Performance Audit",
    [
        ['Page Load & Speed', ''],
        ['TTFB', 'TBD'],
        ['Fully Loaded Time', 'TBD'],
        ['Page Size', 'TBD'],
        ['Total Requests', 'TBD'],
        ['Critical Rendering Path', 'TBD'],
        ['Resource Optimization', 'TBD'],
        ['JS File Count', 'TBD'],
        ['CSS File Count', 'TBD'],
        ['Image Optimization', 'TBD'],
        ['Lazy Loading', 'TBD'],
        ['Minification', 'TBD'],
        ['Mobile Performance', ''],
        ['Viewport Tag', 'TBD'],
        ['Responsive Layout', 'TBD'],
    ]
)

#---------------------------------------------------
# 3️⃣ SEO Audit
#---------------------------------------------------
add_section(
    "3️⃣ SEO Audit",
    [
        ['On-Page SEO', ''],
        ['Page Title', 'TBD'],
        ['Meta Description', 'TBD'],
        ['Canonical Tag', 'TBD'],
        ['H1/H2 Structure', 'TBD'],
        ['Broken Links', 'TBD'],
        ['Indexing & Crawlability', ''],
        ['Robots.txt', 'TBD'],
        ['Meta Robots', 'TBD'],
        ['XML Sitemap', 'TBD'],
        ['HTTP Status Codes', 'TBD'],
        ['Content Quality', ''],
        ['Word Count', 'TBD'],
        ['Keyword Density', 'TBD'],
        ['Duplicate Content Risk', 'TBD'],
        ['Image ALT Attributes', 'TBD'],
    ]
)

#---------------------------------------------------
# 4️⃣ Security
#---------------------------------------------------
add_section(
    "4️⃣ Security Audit",
    [
        ['Transport & Headers', ''],
        ['HTTPS', 'TBD'],
        ['SSL Validity', 'TBD'],
        ['HSTS', 'TBD'],
        ['CSP', 'TBD'],
        ['X-Frame-Options', 'TBD'],
        ['X-Content-Type-Options', 'TBD'],
        ['Referrer-Policy', 'TBD'],
        ['Vulnerabilities', ''],
        ['Mixed Content', 'TBD'],
        ['Open Directories', 'TBD'],
        ['Outdated Libraries', 'TBD'],
        ['Compliance Flags', ''],
        ['GDPR', 'TBD'],
        ['PCI-DSS', 'TBD'],
    ]
)

#---------------------------------------------------
# 5️⃣ Accessibility
#---------------------------------------------------
add_section(
    "5️⃣ Accessibility Audit",
    [
        ['Mandatory Checks', ''],
        ['Image ALT Text', 'TBD'],
        ['Color Contrast', 'TBD'],
        ['Font Readability', 'TBD'],
        ['Keyboard Navigation', 'TBD'],
        ['ARIA Labels', 'TBD'],
        ['Compliance Levels', ''],
        ['WCAG A', 'TBD'],
        ['WCAG AA', 'TBD'],
        ['WCAG AAA', 'TBD'],
    ]
)

#---------------------------------------------------
# 6️⃣ UX & Best Practices
#---------------------------------------------------
add_section(
    "6️⃣ Best Practices & UX",
    [
        ['Code Quality', ''],
        ['HTML Validation', 'TBD'],
        ['Deprecated Tags', 'TBD'],
        ['Inline Styles', 'TBD'],
        ['UX Signals', ''],
        ['CTA Visibility', 'TBD'],
        ['Navigation Clarity', 'TBD'],
        ['Broken UI', 'TBD'],
        ['Above-the-Fold', 'TBD'],
        ['Trust Items', 'TBD'],
    ]
)

#---------------------------------------------------
# 7️⃣ Competitor Benchmarking
#---------------------------------------------------
add_section(
    "7️⃣ Competitor Benchmarking",
    [
        ['Metric', 'Target', 'Competitor A', 'Competitor B'],
        ['Speed', 'TBD', 'TBD', 'TBD'],
        ['SEO Score', 'TBD', 'TBD', 'TBD'],
        ['Mobile Score', 'TBD', 'TBD', 'TBD'],
        ['Domain Authority', 'TBD', 'TBD', 'TBD'],
    ]
)

#---------------------------------------------------
# 8️⃣ Analytics & Tracking
#---------------------------------------------------
add_section(
    "8️⃣ Analytics & Tracking",
    [
        ['Google Analytics', 'TBD'],
        ['Google Tag Manager', 'TBD'],
        ['Facebook Pixel', 'TBD'],
        ['Conversion Tracking', 'TBD'],
        ['Event Tracking Issues', 'TBD'],
    ]
)

#---------------------------------------------------
# 9️⃣ AI Insights
#---------------------------------------------------
add_section(
    "9️⃣ AI-Driven Insights",
    [
        ['Automated Findings', '"High JS usage" / "Missing canonical"'],
        ['Predictive Risk', 'TBD'],
        ['SEO Traffic Loss Risk', 'TBD'],
        ['Performance Risk Estimation', 'TBD'],
    ]
)

#---------------------------------------------------
# 🔟 Action Plan
#---------------------------------------------------
add_section(
    "🔟 Prioritized Action Plan",
    [
        ['Priority', 'Category', 'Issue', 'Impact', 'Recommendation'],
        ['Quick Win', 'SEO', 'TBD', 'High', 'TBD'],
        ['Quick Win', 'Performance', 'TBD', 'Medium', 'TBD'],
        ['Strategic', 'Security', 'TBD', 'High', 'TBD'],
    ]
)

#---------------------------------------------------
# 1️⃣1️⃣ Compliance References
#---------------------------------------------------
add_section(
    "1️⃣1️⃣ Compliance & Standards Reference",
    [
        ['WCAG 2.1', 'Accessibility standards'],
        ['Core Web Vitals', 'Performance metrics'],
        ['OWASP Top 10', 'Security best practices'],
        ['ISO/IEC 27001', 'Information security reference'],
    ]
)

#---------------------------------------------------
# 1️⃣2️⃣ Metadata
#---------------------------------------------------
add_section(
    "1️⃣2️⃣ Audit Metadata",
    [
        ['Tool Version', '1.0.0'],
        ['Audit Engine', 'Hybrid ruleset + manual verification'],
        ['Methodology', 'SEO, Security, UX, WCAG, Core Web Vitals'],
        ['Disclaimer', 'Template generated without live scan'],
        ['Report ID', report_id],
    ]
)

# --------------------------------------------------
# Build PDF
# --------------------------------------------------
doc.build(story)

print("PDF generated:", file_name)
